name: Lint
on: [push]
jobs:
  run-linter:
    name: Run linter
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install linter package
        run: pip install black

      - name: Run linter
        uses: wearerequired/lint-action@v1
        with:
          black: true
